version: "3.1"
services:

    node:
      restart: always
      image: siep_gateway:latest
      container_name: siep-api-gw
      build: .
      volumes:
         - "./app:/src/app"
      ports:
         - "7777:80"
      networks:
        - siep-lan

networks:
  siep-lan:
    driver: bridge
